'use client'

import { useState } from 'react'
import { BookOpen, ChevronDown, ChevronUp, Sparkles, X } from 'lucide-react'
import { Button } from '@/components/ui/button'

interface BuyingGuide {
  make: string
  model: string
  year?: number
  generation?: string
  compact: string
  detailed: string
}

interface BuyingGuideCardProps {
  guide: BuyingGuide
  onDismiss?: () => void
}

export default function BuyingGuideCard({ guide, onDismiss }: BuyingGuideCardProps) {
  const [showDetailed, setShowDetailed] = useState(false)

  return (
    <div className="bg-gradient-to-br from-blue-50 to-purple-50 border-2 border-blue-200 rounded-xl p-4 md:p-6 mb-6 shadow-sm">
      {/* Header */}
      <div className="flex items-start justify-between mb-3">
        <div className="flex items-center gap-3">
          <div className="bg-gradient-to-br from-blue-500 to-purple-600 p-2 rounded-lg">
            <Sparkles className="w-5 h-5 text-white" />
          </div>
          <div>
            <div className="flex items-center gap-2 flex-wrap">
              <h3 className="text-lg font-bold text-gray-900">
                AI Buying Guide
              </h3>
              <span className="text-xs font-medium text-purple-600 bg-purple-100 px-2 py-0.5 rounded-full border border-purple-200">
                AI-Generated
              </span>
            </div>
            <div className="flex items-center gap-2 mt-1">
              <span className="text-sm font-medium text-blue-600 bg-blue-100 px-2 py-0.5 rounded">
                {guide.make} {guide.model}
              </span>
              {guide.generation && (
                <span className="text-xs text-gray-600">
                  {guide.generation}
                </span>
              )}
            </div>
          </div>
        </div>
        {onDismiss && (
          <button
            onClick={onDismiss}
            className="text-gray-400 hover:text-gray-600 transition-colors"
            aria-label="Dismiss guide"
          >
            <X className="w-5 h-5" />
          </button>
        )}
      </div>

      {/* Compact Content */}
      <div
        className="prose prose-sm max-w-none text-gray-700 mb-4"
        dangerouslySetInnerHTML={{ __html: guide.compact }}
      />

      {/* Detailed Content (Expandable) */}
      {showDetailed && (
        <div
          className="prose prose-sm max-w-none text-gray-700 border-t border-blue-200 pt-4 mt-4"
          dangerouslySetInnerHTML={{ __html: guide.detailed }}
        />
      )}

      {/* Toggle Button */}
      <Button
        onClick={() => setShowDetailed(!showDetailed)}
        variant="outline"
        size="sm"
        className="w-full mt-4 border-blue-300 text-blue-700 hover:bg-blue-100 hover:border-blue-400"
      >
        <BookOpen className="w-4 h-4 mr-2" />
        {showDetailed ? (
          <>
            Show Less
            <ChevronUp className="w-4 h-4 ml-2" />
          </>
        ) : (
          <>
            View Full Buying Guide
            <ChevronDown className="w-4 h-4 ml-2" />
          </>
        )}
      </Button>

      {/* Disclaimer */}
      <div className="mt-4 pt-3 border-t border-blue-200">
        <div className="flex items-start gap-2 text-xs text-gray-600">
          <span className="text-amber-500 mt-0.5">⚠️</span>
          <p>
            <strong className="font-semibold text-gray-700">AI-Generated Content:</strong> This guide is generated by artificial intelligence and may contain errors or outdated information. Always conduct independent verification, professional mechanical inspection, and consult multiple sources before making purchase decisions.
          </p>
        </div>
      </div>
    </div>
  )
}
