-- Insert sample listings to simulate user-posted ads
-- Note: These use a test user ID. In production, ensure a valid user exists or create one first

-- First, let's ensure we have a test user (you may need to adjust this based on your auth setup)
-- This assumes you have at least one user in your auth.users table
-- If not, you'll need to create one through Supabase Auth first

DO $$
DECLARE
    test_user_id UUID;
BEGIN
    -- Try to get an existing user ID, or use a placeholder
    SELECT id INTO test_user_id FROM auth.users LIMIT 1;
    
    -- If no user exists, you'll need to create one through Supabase Auth
    -- For now, we'll use a static UUID that you can replace
    IF test_user_id IS NULL THEN
        test_user_id := 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11'::UUID;
    END IF;

    -- Insert sample vehicle listings
    INSERT INTO listings (
        user_id,
        title,
        details,
        description,
        price,
        negotiable,
        make,
        model,
        year,
        mileage,
        fuel_type,
        transmission,
        body_type,
        color,
        engine_capacity,
        status,
        location,
        city,
        district,
        vehicle_type,
        phone,
        whatsapp,
        email,
        pricing_type,
        primary_image_url,
        images,
        posted_date,
        is_sold
    ) VALUES 
    (
        test_user_id,
        'Toyota Prius 2018 - Urgent Sale',
        'Excellent Condition, Full Options',
        'Selling my well-maintained 2018 Toyota Prius. Single owner, full service history available at Toyota Lanka. All original documents, no accidents, first owner. Reason for sale: Migrating abroad. Quick sale needed!',
        4500000,
        true,
        'Toyota',
        'Prius',
        2018,
        45000,
        'Hybrid',
        'Automatic',
        'Sedan',
        'Pearl White',
        1800,
        'active',
        'Colombo 07',
        'Colombo',
        'Colombo',
        'car',
        '94771234567',
        '94771234567',
        'john.seller@example.com',
        'cash',
        'https://images.unsplash.com/photo-1623869317400-91d4957ad5d8?w=800',
        '["https://images.unsplash.com/photo-1623869317400-91d4957ad5d8?w=800", "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=800"]'::jsonb,
        NOW() - INTERVAL '2 days',
        false
    ),
    (
        test_user_id,
        'Honda Vezel 2019 RS Sensing',
        'Top Grade, Low Mileage',
        'Honda Vezel RS with Honda Sensing safety package. Imported brand new. Features include lane assist, adaptive cruise control, collision mitigation braking. Leather seats, sunroof, LED headlights. Showroom condition.',
        6200000,
        false,
        'Honda',
        'Vezel',
        2019,
        28000,
        'Hybrid',
        'Automatic',
        'SUV',
        'Blue Metallic',
        1500,
        'active',
        'Kandy',
        'Kandy',
        'Kandy',
        'car',
        '94812345678',
        '94812345678',
        'vehisales.kandy@example.com',
        'cash',
        'https://images.unsplash.com/photo-1606611013016-c51c19838e42?w=800',
        '["https://images.unsplash.com/photo-1606611013016-c51c19838e42?w=800", "https://images.unsplash.com/photo-1606611013016-969c19e27e46?w=800"]'::jsonb,
        NOW() - INTERVAL '5 days',
        false
    ),
    (
        test_user_id,
        'Suzuki Alto 2015 - Budget Friendly',
        'Ideal First Car, Company Maintained',
        'Perfect car for daily commuting. Very fuel efficient (25km/l in city). Company maintained vehicle with all service records. New tires, battery replaced last month. Minor scratches on bumper reflected in price.',
        1850000,
        true,
        'Suzuki',
        'Alto',
        2015,
        78000,
        'Petrol',
        'Manual',
        'Hatchback',
        'Silver',
        800,
        'active',
        'Gampaha',
        'Gampaha',
        'Gampaha',
        'car',
        '94332345678',
        '94332345678',
        'budget.cars@example.com',
        'cash',
        'https://images.unsplash.com/photo-1609520778163-a16fb3862584?w=800',
        '["https://images.unsplash.com/photo-1609520778163-a16fb3862584?w=800"]'::jsonb,
        NOW() - INTERVAL '1 day',
        false
    ),
    (
        test_user_id,
        'BMW 520d 2016 M Sport Package',
        'Luxury Business Sedan',
        'BMW 520d with M Sport package. Features include M Sport body kit, sports suspension, paddle shifters, harman/kardon sound system, heads up display, parking assistant. Maintained at BMW Prestige. Exchange possible for higher model.',
        8900000,
        true,
        'BMW',
        '520d',
        2016,
        62000,
        'Diesel',
        'Automatic',
        'Sedan',
        'Carbon Black',
        2000,
        'active',
        'Colombo 03',
        'Colombo',
        'Colombo',
        'car',
        '94777888999',
        '94777888999',
        'luxury.motors@example.com',
        'lease',
        'https://images.unsplash.com/photo-1555215858-9dc80a29024c?w=800',
        '["https://images.unsplash.com/photo-1555215858-9dc80a29024c?w=800", "https://images.unsplash.com/photo-1553440569-bcc63803a83d?w=800"]'::jsonb,
        NOW() - INTERVAL '3 days',
        false
    ),
    (
        test_user_id,
        'Nissan Leaf 2018 - Full Electric',
        '100% Electric, Zero Emissions',
        'Nissan Leaf 40kWh battery model. Range 240km on full charge. Home charging point will be provided free. Very low running cost (Rs.3 per km). Qualifies for reduced import tax. Battery health 92%. Silent operation, instant torque.',
        4200000,
        false,
        'Nissan',
        'Leaf',
        2018,
        35000,
        'Electric',
        'Automatic',
        'Hatchback',
        'Arctic White',
        0,
        'active',
        'Nugegoda',
        'Colombo',
        'Colombo',
        'car',
        '94115556666',
        '94115556666',
        'green.vehicles@example.com',
        'cash',
        'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=800',
        '["https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=800"]'::jsonb,
        NOW() - INTERVAL '7 days',
        false
    ),
    (
        test_user_id,
        'Toyota Hiace KDH 2017 High Roof',
        'Ideal for Tours, 15 Seater',
        'Toyota Hiace Super GL high roof model. Dual AC, reclining seats, luggage carrier, reverse camera. Currently used for airport transfers. Full insurance, revenue license up to date. Selling due to fleet upgrade.',
        7500000,
        true,
        'Toyota',
        'Hiace',
        2017,
        120000,
        'Diesel',
        'Manual',
        'Van',
        'White',
        2800,
        'active',
        'Negombo',
        'Negombo',
        'Gampaha',
        'van',
        '94312223333',
        '94312223333',
        'tours.transport@example.com',
        'lease',
        'https://images.unsplash.com/photo-1581540222194-0def2dda95b8?w=800',
        '["https://images.unsplash.com/photo-1581540222194-0def2dda95b8?w=800"]'::jsonb,
        NOW() - INTERVAL '4 days',
        false
    ),
    (
        test_user_id,
        'Mazda CX-5 2020 Premium Edition',
        'Fully Loaded Crossover SUV',
        'Top of the line CX-5 with all options. Features include 360 camera, blind spot monitoring, lane keep assist, adaptive LED headlights, power tailgate, BOSE sound, ventilated seats. Under agent warranty.',
        11500000,
        false,
        'Mazda',
        'CX-5',
        2020,
        15000,
        'Petrol',
        'Automatic',
        'SUV',
        'Soul Red Crystal',
        2500,
        'active',
        'Battaramulla',
        'Battaramulla',
        'Colombo',
        'car',
        '94777123456',
        '94777123456',
        'premiumsuvs@example.com',
        'cash',
        'https://images.unsplash.com/photo-1609207753409-3c2051e634b8?w=800',
        '["https://images.unsplash.com/photo-1609207753409-3c2051e634b8?w=800"]'::jsonb,
        NOW() - INTERVAL '6 days',
        false
    ),
    (
        test_user_id,
        'Honda Civic 2018 Turbo SR',
        'Sports Package, Modified',
        'Honda Civic turbo with sports package. Modifications include lowered suspension, 18 inch alloys, sports exhaust, carbon fiber spoiler. All modifications professionally done with receipts. Back to stock parts available.',
        5800000,
        true,
        'Honda',
        'Civic',
        2018,
        52000,
        'Petrol',
        'Automatic',
        'Sedan',
        'Rally Red',
        1500,
        'active',
        'Maharagama',
        'Maharagama',
        'Colombo',
        'car',
        '94779998888',
        '94779998888',
        'sports.cars.lk@example.com',
        'cash',
        'https://images.unsplash.com/photo-1616788593665-e00a388e8c37?w=800',
        '["https://images.unsplash.com/photo-1616788593665-e00a388e8c37?w=800"]'::jsonb,
        NOW() - INTERVAL '10 days',
        false
    ),
    (
        test_user_id,
        'Mitsubishi Montero 2015 4WD',
        'True Off-Road Beast',
        'Mitsubishi Montero Sport 4WD. Features include diff lock, hill descent control, off-road mode. New all-terrain tires, bull bar, winch, roof rack. Perfect for adventure enthusiasts. Some off-road pin stripes.',
        6700000,
        true,
        'Mitsubishi',
        'Montero',
        2015,
        95000,
        'Diesel',
        'Automatic',
        'SUV',
        'Black',
        3200,
        'active',
        'Ratnapura',
        'Ratnapura',
        'Ratnapura',
        'suv',
        '94452223333',
        '94452223333',
        'offroad.lk@example.com',
        'lease',
        'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800',
        '["https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800"]'::jsonb,
        NOW() - INTERVAL '8 days',
        false
    ),
    (
        test_user_id,
        'Toyota Aqua 2014 S Grade',
        'Most Fuel Efficient, Reliable',
        'Toyota Aqua S grade with push start, alloy wheels. Average fuel consumption 28km/l. New hybrid battery with warranty. Ideal for Uber/PickMe. Some minor dents. Priced for quick sale. First come first serve.',
        2950000,
        false,
        'Toyota',
        'Aqua',
        2014,
        125000,
        'Hybrid',
        'Automatic',
        'Hatchback',
        'Light Blue',
        1500,
        'active',
        'Moratuwa',
        'Moratuwa',
        'Colombo',
        'car',
        '94382223333',
        '94382223333',
        'eco.cars@example.com',
        'cash',
        'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800',
        '["https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800"]'::jsonb,
        NOW() - INTERVAL '12 days',
        false
    );

    -- Mark some as promoted for visibility
    UPDATE listings 
    SET 
        is_featured = true,
        featured_until = NOW() + INTERVAL '7 days'
    WHERE title LIKE '%Toyota Prius%' AND user_id = test_user_id;

    UPDATE listings 
    SET 
        is_urgent = true,
        urgent_until = NOW() + INTERVAL '3 days'
    WHERE title LIKE '%Urgent Sale%' AND user_id = test_user_id;

    UPDATE listings 
    SET 
        is_boosted = true,
        boosted_until = NOW() + INTERVAL '5 days',
        boost_score = 10
    WHERE title LIKE '%Honda Vezel%' AND user_id = test_user_id;

    RAISE NOTICE 'Sample listings inserted successfully';
    
EXCEPTION
    WHEN OTHERS THEN
        RAISE NOTICE 'Error inserting sample listings: %', SQLERRM;
        RAISE NOTICE 'You may need to create a user first through Supabase Auth';
END $$;